### ISSUE TITLE
多账户登录有问题

### ISSUE THREAD

**Issue by jaCsharp** [nonultimate/CTPSharp#1]
楼主您好，我目前在用websocket+ctp 来做模拟交易，
我发现不同的用户登录交易，他们会互踢，假如a先登录，然后b登录，最后登录的b会踢掉先前登录的a。
你有这种情况吗？

**Comment by nonultimate** [comment]
目前这种封装不支持多账户同时登录，不过可以用domain作用域启动多个实例变相实现多账户同时登录

**Comment by jaCsharp** [comment]
ok

**Comment by nonultimate** [comment]
最新版本已经支持多账户登录了
