### ISSUE TITLE
执行回调函数后，网络连接断开

### ISSUE THREAD

**Issue by caoyuanfeng** [nonultimate/CTPSharp#6]
在快期下单成交，回调函数执行了
public void RtnTrade(ref CThostFtdcTradeField pTrade)
        {
            Console.WriteLine("成交查询成功, TradeID: {0}", pTrade.TradeID);
        }
但是执行完后，网络就断开了，执行了下面的回调，nReasion是4097，这是什么原因？
_api.OnDisconnected += new TradeApi.Disconnected((int nReasion) =>
            {
                _isConnected = false;
            });

**Comment by nonultimate** [comment]
4097是网络读失败，检查下前置服务器地址，或者换个地址试试

**Comment by caoyuanfeng** [comment]
发现断开后，立候就重连上了，用的是simnow工作时间的地址
